version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/appdata/node_modules
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
